# Site settings
title: BayesOpt 2016
description: "
NIPS Workshop on Bayesian Optimization
<br>December 10, 2016
<br>Barcelona, Spain"
baseurl: ""
url: "http://bayesopt.github.io"

# Build settings
markdown: kramdown
permalink: pretty

defaults:
    -
        scope:
            path: ""
        values:
            layout: "default"

